# Change experiment name
name: 'arc_classifier'

seed: 0

train_on_first: true


base_path: '..'  # base path where model weights , tensorboard will be saved
# base_path: '/Users/jianhansong/my-app'
training_dir: 'trained_models'  # base_path + training_dir
tensorboard_dir: 'runs' # base_path + tensorboard_dir

data:
    base_path: 'data/model_build_inputs'   # base_path + data.base_path (this path) is where all data is saved
    # base_path + data.base_path + data_type_filename
    # base_path: 'data/small_data'
    route_filename: 'route_data.json'
    sequence_filename: 'actual_sequences.json'
    travel_times_filename: 'travel_times.json'
    package_data_filename: 'package_data.json'

    train_split: 0.8  # Training data is 70% and test data is 30%
    use_cache: false # Cache data as pickle file.

    slice_begin: 0
    slice_end: 200
    num_link_features: 2
    num_route_features: 2
    num_stop_features: 7
    route_score: ['High', 'Low']
    num_neighbors: 0  # Num of surrounding stops to use for same feature set.

model:
    hidden_size: 5

batch_size: 32
num_train_epochs: 100

# Optimizer
learning_rate: 0.001
momentum: 0.9