# Change experiment name
name: 'eval'

seed: 0


base_path: '..'  # base path where model weights , tensorboard will be saved
# base_path: '/Users/jianhansong/my-app'
training_dir: 'trained_models'  # base_path + training_dir
tensorboard_dir: 'runs' # base_path + tensorboard_dir

data:
    base_path: 'data/model_apply_inputs'   # base_path + data.base_path (this path) is where all data is saved
    # base_path + data.base_path + data_type_filename
    # base_path: 'data/small_data'
    route_filename: 'new_route_data.json'
    travel_times_filename: 'new_travel_times.json'
    package_data_filename: 'new_package_data.json'

    train_split: 0.0  
    use_cache: false
    slice_begin: 0
    slice_end: 1000
    num_link_features: 10
    num_route_features: 1
    route_score: ['High']
    num_neighbors: 0  # Num of surrounding stops to use for same feature set.

batch_size: 500

save_path: '../trained_models/no_station_code/best_score_no_station_code.pt'
