# Change experiment name
name: 'linear_irl_batch_all_routes_eval'

seed: 0
train_split: 0.7  # Training data is 70% and test data is 30%


base_path: '..'  # base path where model weights , tensorboard will be saved
# base_path: '/Users/jianhansong/my-app'
training_dir: 'trained_models'  # base_path + training_dir
tensorboard_dir: 'runs' # base_path + tensorboard_dir

data:
    base_path: 'data/model_build_inputs'   # base_path + data.base_path (this path) is where all data is saved
    # base_path + data.base_path + data_type_filename
    # base_path: 'data/small_data'
    route_filename: 'route_data.json'
    sequence_filename: 'actual_sequences.json'
    travel_times_filename: 'travel_times.json'
    package_data_filename: 'package_data.json'
    slice_begin: 0
    slice_end: 500
    route_score: 'medium'
    num_link_features: 1
    num_route_features: 1
    use_cache: false
    num_neighbors: 0  # Num of surrounding stops to use for same feature set.

theta: 35.38970464
lamb: 0.24744489418041002