# Change experiment name
name: 'eval'

seed: 0


base_path: '..'  # base path where model weights , tensorboard will be saved
# base_path: '/Users/jianhansong/my-app'
training_dir: 'trained_models'  # base_path + training_dir
tensorboard_dir: 'runs' # base_path + tensorboard_dir

data:
    base_path: 'data/model_build_inputs'   # base_path + data.base_path (this path) is where all data is saved
    # base_path + data.base_path + data_type_filename
    # base_path: 'data/small_data'
    route_filename: 'route_data.json'
    sequence_filename: 'actual_sequences.json'
    travel_times_filename: 'travel_times.json'
    package_data_filename: 'package_data.json'
    
    train_split: 0.0  # Training data is 70% and test data is 30%

    use_cache: false
    slice_begin: 2000
    slice_end: 2500
    num_link_features: 10
    num_route_features: 2
    route_score: 'high'
    num_neighbors: 0  # Num of surrounding stops to use for same feature set.

batch_size: 32

save_path: '/Users/Somi/amazon_challenge/trained_models/10_routes_log/best_score_10_routes_log.pt'
