# Change experiment name
name: 'arc_classifier_small'

seed: 0
train_split: 0.7  # Training data is 70% and test data is 30%
device: 'cpu'

base_path: '../'
route_filename: 'data/small_data/route_data.json'
sequence_filename: 'data/small_data/actual_sequences.json'
travel_times_filename: 'data/small_data/travel_times.json'
package_data_filename: 'data/small_data/package_data.json'

dataset:
    link_features_size: 1
    route_features_size: 3

model:
    hidden_size: 256

batch_size: 16
num_train_epochs: 1000

# Optimizer
learning_rate: 0.001
momentum: 0.9